"""Fit and serialise the IDX Carbon forecaster.

*** TRAINED ON SYNTHETIC DATA. NOT A REAL FORECASTING MODEL. ***

This reads ml/data/price_history_SYNTHETIC.csv, a fabricated placeholder
series generated by ml/generate_synthetic_prices.py (see that script's
docstring, and ml/DATA_PROVENANCE.md, for why). The artifact this script
writes must be retrained on real IDX Carbon data -- and the filename must
drop the ``_SYNTHETIC`` suffix -- before any forecast it produces is shown
to anyone as real.

Run manually; the artifact is committed to the repo. Nothing trains at
request time.
"""

import pickle
import sys
from pathlib import Path

import pandas as pd
from prophet import Prophet

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ml/data/price_history_SYNTHETIC.csv"
OUT = ROOT / "carbonatix/backend/app/forecasting/artifacts/idx_carbon_SYNTHETIC.pkl"


def main() -> None:
    print(
        "WARNING: training on SYNTHETIC price history "
        f"({SOURCE.name}). This model is NOT fit to real market data.",
        file=sys.stderr,
    )

    df = pd.read_csv(SOURCE, comment="#", parse_dates=["observed_on"])
    series = (
        df[["observed_on", "idx_carbon_idr_per_ton"]]
        .dropna()
        .rename(columns={"observed_on": "ds", "idx_carbon_idr_per_ton": "y"})
    )

    # IDX Carbon launched September 2023 and trades thinly. Yearly seasonality
    # cannot be estimated from a short, sparse series -- asking Prophet for it
    # produces a confident-looking curve fitted to noise. This matters even
    # more here because the series is synthetic and sparse by construction:
    # there is no real seasonal signal in it to find.
    model = Prophet(
        daily_seasonality=False,
        weekly_seasonality=False,
        yearly_seasonality=False,
        interval_width=0.80,
    )

    if len(series) < 60:
        raise SystemExit(
            f"Only {len(series)} observations. Report this honestly: the "
            f"confidence band is wide because the market is illiquid."
        )

    model.fit(series)

    # Provenance travels with the pickle itself, not just the filename, so
    # the "SYNTHETIC" fact survives a copy/rename that drops the filename
    # marker (e.g. a deploy step that normalises artifact names). Task 11
    # reads this attribute by name to surface a synthetic flag downstream.
    # Same attribute name and shape as train_nickel.py -- do not diverge.
    model.carbonatix_provenance = {
        "synthetic": True,
        "generated_on": "2026-08-04",
        "generator": "ml/generate_synthetic_prices.py",
        "seed": 20260804,
        "source_csv": "ml/data/price_history_SYNTHETIC.csv",
        "warning": (
            "SYNTHETIC DATA - NOT REAL MARKET PRICES. Must be replaced "
            "before any published result or presentation. See "
            "ml/DATA_PROVENANCE.md"
        ),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(pickle.dumps(model))
    print(
        f"Wrote {OUT} from {len(series)} SYNTHETIC observations "
        f"({series.ds.min().date()} to {series.ds.max().date()})"
    )


if __name__ == "__main__":
    main()
